;;; !!! This configuration is handled by HelloImGui and stores several Ini Files, separated by markers like this:
           ;;;<<<INI_NAME>>>;;;

;;;<<<ImGui_655921752_Default>>>;;;
[Window][Debug##Default]
Pos=60,60
Size=400,400
Collapsed=0
LastUsed=20260928

[Window][状态]
Pos=0,760
Size=1440,140
Collapsed=0
LastUsed=20260928

[Window][审核结果]
Pos=1075,24
Size=404,485
Collapsed=0
LastUsed=20260928

[Window][图片与标注]
Pos=290,24
Size=351,335
Collapsed=0
LastUsed=20260928

[Window][数据导航]
Pos=0,24
Size=286,332
Collapsed=0
LastUsed=20260928

[Docking][Data]


;;;<<<Layout_655921752_Default>>>;;;

;;;<<<HelloImGui_Misc>>>;;;
[Layout]
Name=Default
[StatusBar]
Show=false
ShowFps=true
[Theme]
Name=DarculaDarker

;;;<<<SplitIds>>>;;;
{"gImGuiSplitIDs":{}}
